language: go
sudo: false
go:
  - 1.13
  - tip
install:
  - go get -t ./...
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
script:
  - go test -v -cover -covermode=count -coverprofile=cover.prof
  - cat cover.prof
